#!/usr/bin/env bash
# Boot Expo for phone testing.
#
# Detects the host's LAN IP, writes mobile/.env with LAN-addressable URLs for
# the backend + Supabase, and starts the Expo dev server. The phone connects
# via Expo Go (scan the QR code) and the bundle's API client uses LAN URLs
# instead of 127.0.0.1.
#
# Usage:
#   ./scripts/mobile-up.sh          # LAN mode (default) — phone via Expo Go
#   ./scripts/mobile-up.sh --tunnel # ngrok-style tunnel (blocked on some corp nets)
#   ./scripts/mobile-up.sh --ios    # iOS Simulator — zero network required
#   ./scripts/mobile-up.sh --web    # browser, localhost only (no native modules)
#   HOST_IP=10.0.0.5 ./scripts/mobile-up.sh   # force a specific IP
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if [[ -t 1 ]]; then GRN=$'\033[32m'; YEL=$'\033[33m'; RED=$'\033[31m'; CYA=$'\033[36m'; BLD=$'\033[1m'; RST=$'\033[0m'
else GRN=''; YEL=''; RED=''; CYA=''; BLD=''; RST=''; fi

MODE="lan"
for arg in "$@"; do
  case "$arg" in
    --tunnel) MODE="tunnel" ;;
    --lan)    MODE="lan" ;;
    --ios)    MODE="ios" ;;
    --web)    MODE="web" ;;
    *) echo "unknown flag: $arg"; exit 1 ;;
  esac
done

# ─── Host selection ──────────────────────────────────────────────────────────
# Simulator / browser run on this machine — use localhost, no network needed.
# Phone modes need a routable host.
if [[ "$MODE" == "ios" || "$MODE" == "web" ]]; then
  HOST_IP="127.0.0.1"
  echo "${CYA}[kitty]${RST} ${BLD}$MODE${RST} mode — using localhost"
else

# ─── Detect LAN IP ───────────────────────────────────────────────────────────
detect_ip() {
  # 1. env override
  [[ -n "${HOST_IP:-}" ]] && { echo "$HOST_IP"; return; }
  # 2. macOS: WiFi usually en0
  if command -v ipconfig >/dev/null 2>&1; then
    for iface in en0 en1 en2 en3; do
      ip=$(ipconfig getifaddr "$iface" 2>/dev/null || true)
      [[ -n "$ip" ]] && { echo "$ip"; return; }
    done
  fi
  # 3. Linux / fallback
  ip route get 8.8.8.8 2>/dev/null | awk '/src/ { for (i=1;i<=NF;i++) if ($i=="src") print $(i+1) }' | head -1
}

HOST_IP=$(detect_ip)
if [[ -z "$HOST_IP" ]]; then
  echo "${RED}couldn't detect a LAN IP — set HOST_IP=x.y.z.w ./scripts/mobile-up.sh${RST}"
  exit 1
fi
echo "${CYA}[kitty]${RST} LAN IP: ${BLD}$HOST_IP${RST}"
fi  # close the host-selection branch

# ─── Read supabase anon key from root .env ───────────────────────────────────
if [[ ! -f .env ]]; then
  echo "${RED}.env not found — run ./start.sh first${RST}"
  exit 1
fi
SUPABASE_ANON_KEY=$(grep -E '^SUPABASE_ANON_KEY=' .env | cut -d= -f2- | tr -d '"')
if [[ -z "$SUPABASE_ANON_KEY" ]]; then
  echo "${YEL}[kitty]${RST} SUPABASE_ANON_KEY is empty in .env — mobile auth will fail"
fi

# ─── Write mobile/.env ───────────────────────────────────────────────────────
cat > mobile/.env <<EOF
# Generated by scripts/mobile-up.sh — DO NOT EDIT by hand.
# Regenerate when LAN IP changes: ./scripts/mobile-up.sh
EXPO_PUBLIC_API_BASE_URL=http://${HOST_IP}:8000
EXPO_PUBLIC_SUPABASE_URL=http://${HOST_IP}:54321
EXPO_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
EOF
echo "${GRN}✓${RST} wrote mobile/.env (host=${HOST_IP})"

# ─── Probe reachability ──────────────────────────────────────────────────────
echo "${CYA}[kitty]${RST} probing services from the LAN IP..."
probe() {
  local url=$1 name=$2
  if curl -sf -m 3 "$url" >/dev/null 2>&1; then
    echo "  ${GRN}✓${RST} $name @ $url"
  else
    echo "  ${RED}✗${RST} $name @ $url (phone won't reach this either!)"
  fi
}
probe "http://${HOST_IP}:8000/health" backend
probe "http://${HOST_IP}:54321/auth/v1/health" supabase

# ─── Launch Expo ─────────────────────────────────────────────────────────────
echo ""
echo "${BLD}──── Expo ────${RST}"
echo "  · open Expo Go on your phone (iOS / Android)"
echo "  · scan the QR code printed below"
echo "  · phone must be on the same WiFi as this machine"
cd "$REPO_ROOT/mobile"
case "$MODE" in
  tunnel)
    echo "  · (tunnel mode: works across networks, slower)"
    exec npx -y expo start --tunnel --clear
    ;;
  ios)
    # Boot the simulator first so the openurl step doesn't race.
    if ! xcrun simctl list devices booted | grep -q iPhone; then
      echo "${CYA}[kitty]${RST} booting iPhone 16 Pro simulator..."
      xcrun simctl boot "iPhone 16 Pro" 2>/dev/null || true
    fi
    open -a Simulator
    echo "  · hand off to iOS Simulator (Expo Go auto-installs if missing)"
    exec npx -y expo start --localhost --ios --clear
    ;;
  web)
    echo "  · web mode: runs in browser at http://localhost:8081 (native modules stubbed)"
    exec npx -y expo start --localhost --web --clear
    ;;
  lan)
    echo "  · scan QR with Expo Go on a phone on the same WiFi"
    exec npx -y expo start --lan --clear
    ;;
esac
